name: flutter_week4_exercise
description: Flutter Week 4 Exercise - ListView, GridView, SharedPreferences, Async, Isolate

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  # SharedPreferences để lưu dữ liệu cục bộ
  shared_preferences: ^2.2.2
  # Định dạng ngày giờ
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
